[package]
name = "lnpbp"
version = "0.1.0"
license = "MIT"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Library implementing LNPBPs specifications & standards"
keywords = ["bitcoin", "lightning", "blockchain", "layer-2", "cryptography"]
readme = "README.md"
edition = "2018"

[lib]
name = "lnpbp"
path = "src/lib.rs"

[dependencies]
bitcoin = { git = "https://github.com/pandoracore/rust-bitcoin", branch = "develop", features = [ "use-serde" ] }
num-integer = "0.1.42"
hex = { version = "=0.3.2", optional = true }

[dev-dependencies]
hex = "=0.3.2"
