[package]
name = "lnpbp"
version = "0.1.0"
license = "MIT"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Library implementing LNPBPs specifications & standards"
keywords = ["bitcoin", "lightning", "blockchain", "layer-2", "cryptography"]
readme = "README.md"
edition = "2018"

[lib]
name = "lbpbp"
path = "src/lib.rs"

[dependencies]
bitcoin = { git = "https://github.com/pandoracore/rust-bitcoin.git", branch = "develop" }
bitcoin_hashes = { git = "https://github.com/pandoracore/bitcoin_hashes.git", branch = "hashnewtype-fix" }

[dependencies.secp256k1]
version = "0.15.0"
features = [ "rand" ]
